config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to:'users#new'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, length: {minimum:3, maximum:25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
             uniqueness: {case_sensitive: false},
             length: {minimum:3, maximum:25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, length: {maximum: 105},
             uniqueness: {case_sensitive: false},
             format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end


  def new
    @article = Article.new
  end


  def edit

  end


  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was succesfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end


  def update
    if @article.update(article_params)
      flash[:success] = "Article was succesfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end


  def show

  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was succesfully deleted"
    redirect_to articles_path
  end


  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
    flash[:danger] = "You can only edit or delete your own article"
    redirect_to root_path
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
      if @category.save
        flash[:success] = "Category was created succesfully"
        redirect_to categories_path
      else
        render 'new'
      end
  end

  def show

  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 def new

 end

 def create
   user = User.find_by(email: params[:session][:email].downcase)
   if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
   flash[:success] = "You have succesfully logged in"
   redirect_to user_path(user)
   else
     flash.now[:danger] = "There was something wrong with your login information"
     render 'new'
   end
 end

 def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page:5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was succesfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page:5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
    flash[:danger] = "You can only edit your own account"
    redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = {size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class:"pt-2 pb-2 mx-auto d-block rounded-circle")
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-sm-8 offset-sm-2">
      <div class="card mb-4">
        <div class="card-body">
          <div class="card-title">
            <%= link_to article.title, article_path(article) %>
          </div>
          <div class="card-title border-top pt-2">
            <%= truncate(article.description, length: 100) %>
            <div class="article-meta-details border-top mt-3 text">
              <small>created by: <%= article.user.username if article.user %>,
                     <%= time_ago_in_words(article.created_at) %> ago,
                     last updated: <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>
          <% if logged_in? && (current_user == article.user || current_user.admin?) %>
            <div class="pt-2 border-top">
              <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this article", article_path(article), method: :delete,
                                                 data: {confirm:  "Are you sure you want to delete the article?"},
                                                 class: "btn btn-xs btn-danger" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="pt-4">
<h4 class="text-center pt-5">Edit existing article</h4>

<%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h4 class="text-center">Listing all articles</h4>
<div class="d-flex justify-content-center">
  <%= will_paginate @articles, list_classes:%w(pagination), previous_label:"Previous", next_label: "Next" %>
</div>
<%= render 'article', obj: @articles %>
<div class="d-flex justify-content-center">
  <%= will_paginate @articles, list_classes:%w(pagination), previous_label:"Previous", next_label: "Next" %>
</div>

app/views/articles/new.html.erb
<h4 class="text-center">Create an article</h4>

<%= render 'form' %>

app/views/articles/show.html.erb
<h4 class="text-center pt-5">Title: <%= @article.title %></h4>

<% if @article.user %>
<div class="col-sm-8 offset-sm-2">
  <div class="card">
    <div class="card-body">
      <ul class="text-center list-unstyled mb-4">
        <div class="row">
          <div class="col-sm-4 offset-sm-4">
            <li>Created by:</li>
            <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
                </small></li>
         </div>
       </div>
     </ul>
  <% end %>
  <h4 class="text-center text-weight-bold">Description:</h4>

  <%= simple_format(@article.description) %>

  <div class="pt-2 border-top">
    <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete this article", article_path(@article), method: :delete,
                                         data: {confirm:  "Are you sure you want to delete the article?"},
                                         class: "btn btn-xs btn-danger" %>
    <% end %>
    <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>
</div>
</div>

app/views/categories/index.html.erb
<h3 class="text-center">Listing All Categories</h3>
<div class="d-flex justify-content-center">
  <%= will_paginate %>
</div>
<% @categories.each do |category| %>
  <ul class="list-unstyled text-center">
    <div class="row">
      <div class="card col-sm-4 offset-sm-4">
        <div class="card-body">
          <li class="card-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </li>
        </div>
      </div>
    </div>
  </ul>
<% end %>
<div class="d-flex justify-content-center">
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h3 class="text-center">Create new category</h3>

<%= render 'shared/errors', obj:@category %>

<%= form_for @category do |f| %>
  <div class="form-group pt-2">
    <%= f.label :category %>
    <%= f.text_field :name, class:"form-control", placeholder:"Category name", autofocus:true %>
  </div>

  <div class="pb-5">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  <% end %>
  <div>
    <%= link_to "Cancel and Back to articles listing", articles_path %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, facere.</small>
      <nav>
        <ul>
          <li><%= link_to "About", about_path %></li>
        </ul>
      </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-sm-10 offset-sm-1 pt-3">
    <% flash.each do |name, msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-light">
  <%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        <% end %>
      </li>
      <li class="nav-item mr-5">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
      <li class="nav-item ml-5">
        <form class="form-inline my-2 my-lg-0 mr-5">
         <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0 mr-5" type="submit">Search</button>
        </form>
        </li>
    </ul>
      <% if logged_in? %>
      <%= link_to "Log out", logout_path, method: :delete, class:"nav-link text-white ml-5" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Your Profile <%= "Admin" if current_user.admin? %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>

          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% else %>
      <%= link_to "Login", login_path, class:"nav-link text-white ml-5" %>
      <%= link_to "Sign up", signup_path, class:"nav-link text-white ml-5" %>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Alpha-Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
   <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
      <div class="container mt-3">
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>

<h2>We love dogs</h2>

app/views/pages/home.html.erb
<div class="text-center pt-3">
<h1>ALPHA BLOG</h1>
  <% if !logged_in? %>
  <%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-lg" %>
  <% end %>
<div class="jumbotron text-center mt-3">
</div>
</div>

app/views/shared/_errors.html.erb
<div class="pt-5 pb-2">
<% if obj.errors.any? %>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="card text-danger border border-danger">
      <div class="card-header">
        <h4 class="card-title">

          <%= pluralize(obj.errors.count, "error") %></br>
          Prohibited this article from being saved:
        </h4>
          <div class="card-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>

<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <%= form_for @user do |f| %>
    <div class="form-group pt-2">
      <%= f.label :username %>
      <%= f.text_field :username, class:"form-control", placeholder:"Enter username", autofocus:true %>
    </div>
    <div class="form-group pt-2">
      <%= f.label :email %></br>
      <%= f.email_field :email, class:"form-control", placeholder:"Enter email", autofocus:true %>
    </div>
    <div class="form-group pt-2">
      <%= f.label :password %></br>
      <%= f.password_field :password,class:"form-control", placeholder:"Enter password", autofocus:true %>
    </div>
    <div class="pb-5">
      <%= f.submit(@user.new_record? ? "Signup" : "Update account", class: "btn btn-primary") %>
    </div>
    <% end %>
    <div>
      <%= link_to "Cancel and Back to articles listing", articles_path %>
  </div>
  </div>
</div>

app/views/users/edit.html.erb
<h3 class="text-center">Edit Your Account</h3>
<%= render 'form' %>

app/views/users/index.html.erb
<h3 class="text-center">All Alpha Bloggers</h3>
<div class="d-flex justify-content-center">
  <%= will_paginate @articles, list_classes:%w(pagination), previous_label:"Previous", next_label: "Next" %>
</div>
<% @users.each do |user| %>

  <ul class="text-center list-unstyled mb-4">
    <div class="row">
      <div class="card col-sm-4 offset-sm-4">
        <li><%= link_to gravatar_for(user), user_path(user) %></li>
        <li class="article-title">
          <%= link_to user.username, user_path(user) %>
        </li>
        <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        <% if logged_in? and current_user.admin? %>
          <li><%= link_to "Delete this user", user_path(user), method: :delete,
                  data: {confirm: "Are you sure you want to delete the user and all their articles?"} %></li>
        <% end %>

     </div>
   </div>
 </ul>

<% end %>
<div class="d-flex justify-content-center">
  <%= will_paginate %>
</div>
</div>

app/views/users/new.html.erb
<h3 class="text-center"> Sign up for Alpha Blog </h3>

<%= render 'form' %>

app/views/users/show.html.erb
<h3 class="text-center">Welcome to <%= @user.username %>'s page</h3>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4 center mx-auto d-block">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 class="text-center pt-2"><%= @user.username %>'s articles</h4>
<div class="d-flex justify-content-center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="d-flex justify-content-center">
  <%= will_paginate @user_articles %>
</div>